In [27]:
import numpy as np
import cv2 as cv

sample_color = np.ones((400,400,3),np.uint8())*[0,0,255]




# hsv = cv.cvtColor(sample_color,cv.COLOR_RGB2BGR)

# low_l = np.array([10,100,100])
# upp_l = np.array([30,255,255])

# mask = cv.inRange(hsv,low_l,upp_l)
# cv.imshow("sample",sample_color)
# cv.imshow("mask",sample_color)
print(sample_color)

cv.waitKey(0)
cv.destroyAllWindows()

[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]
